name: Test macgputils on Mac (Intel/ARM)

on: [push, workflow_dispatch]

jobs:
  test_macgputils:
    runs-on: macos-13  # This uses the latest macOS (typically M1-based)

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install macgputils

      - name: Run powermetrics to check GPU stats
        run: |
          echo "Running powermetrics to check GPU stats"
          sudo powermetrics --samplers gpu_power > powermetrics_output.txt || echo "Timeout or failure"
          cat powermetrics_output.txt

      - name: Check architecture and run eg.py on M1 only
        run: |
          ARCH=$(uname -m)
          echo "Detected architecture: $ARCH"
          if [[ "$ARCH" == "arm64" ]]; then
            echo "Running on Apple Silicon (M1 or newer)..."
            sudo python3 eg.py
          else
            echo "Not Apple Silicon, skipping eg.py"
          fi
