name: Test macgputils with sudo

on: [push, workflow_dispatch]

jobs:
  test_macgputils:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install macgputils

      - name: Run macgputils_test.py with sudo
        run: sudo python3 eg.py
