name: Test macgputils with sudo

on: [push, workflow_dispatch]

jobs:
  test_macgputils:
    runs-on: macos-13  # macOS 13 runner

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install macgputils

      - name: Run powermetrics to check GPU stats
        run: |
          echo "Running powermetrics to check GPU stats"
          # Increase timeout to 5 minutes (300s)
          sudo timeout 300s powermetrics --samplers gpu_power > powermetrics_output.txt || echo "Timeout or failure"
          cat powermetrics_output.txt  # Display the output in the log

      - name: Check if powermetrics worked correctly
        run: |
          echo "Checking the powermetrics output for errors"
          if [[ -s powermetrics_output.txt ]]; then
            echo "powermetrics output available"
          else
            echo "No output from powermetrics. Something went wrong."
          fi

      - name: Run macgputils_test.py with sudo
        run: |
          sudo python3 eg.py  # Run the Python test script with sudo
