name: Test macgputils on Mac (Intel/ARM)

on: [push, workflow_dispatch]

jobs:
  test_macgputils:
    runs-on: macos-14  # Supports both Intel and Apple Silicon

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install macgputils

      - name: Detect architecture and log system info
        run: |
          echo "Architecture: $(uname -m)"
          uname -a
          system_profiler SPHardwareDataType

      - name: Conditionally run powermetrics or fallback
        run: |
          ARCH=$(uname -m)
          if [[ "$ARCH" == "x86_64" ]]; then
            echo "Running on Intel-based Mac. Using powermetrics..."
            sudo powermetrics --samplers gpu_power --timeout 30 > powermetrics_output.txt || echo "powermetrics failed"
          else
            echo "Running on Apple Silicon. Using system_profiler as fallback..."
            system_profiler SPDisplaysDataType > powermetrics_output.txt || echo "Fallback failed"
          fi
          echo "----- Output -----"
          cat powermetrics_output.txt

      - name: Run macgputils test script with sudo
        run: |
          sudo python3 eg.py
